import Layout from "@components/Layout";
import { type AppType } from "next/dist/shared/lib/utils";
import Head from "next/head";
import "@styles/globals.css";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
    <Head>
      <title>Hopper!</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <Component {...pageProps} />
    </Layout>
    </>
    
  )
};

export default MyApp;
